// <auto-generated />
namespace LoteAutosGit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addIneComprador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIneComprador));
        
        string IMigrationMetadata.Id
        {
            get { return "201702180648183_add-IneComprador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
